# _WTS_INFO_CLASS
WTSInitialProgram, WTSApplicationName, WTSWorkingDirectory, WTSOEMId, \
    WTSSessionId, WTSUserName, WTSWinStationName, WTSDomainName, WTSConnectState, WTSClientBuildNumber, \
    WTSClientName, WTSClientDirectory, WTSClientProductId, \
    WTSClientHardwareId, WTSClientAddress, WTSClientDisplay, \
    WTSClientProtocolType, WTSIdleTime, WTSLogonTime, WTSIncomingBytes, WTSOutgoingBytes, \
    WTSIncomingFrames, WTSOutgoingFrames, WTSClientInfo, WTSSessionInfo, \
    WTSSessionInfoEx, WTSConfigInfo, WTSValidationInfo, WTSSessionAddressV4, \
    WTSIsRemoteSession = range(0, 30)

# _WTS_CONNECTSTATE_CLASS
WTSActive, WTSConnected, WTSConnectQuery, WTSShadow, WTSDisconnected, WTSIdle, \
    WTSListen, WTSReset, WTSDown, WTSInit = range(0, 10)
    
#  
WTS_CONSOLE_CONNECT = 0x1
WTS_CONSOLE_DISCONNECT = 0x2
WTS_REMOTE_CONNECT = 0x3
WTS_REMOTE_DISCONNECT = 0x4
WTS_SESSION_LOGON = 0x5
WTS_SESSION_LOGOFF = 0x6
WTS_SESSION_LOCK = 0x7
WTS_SESSION_UNLOCK = 0x8
WTS_SESSION_REMOTE_CONTROL = 0x9
WTS_SESSION_CREATE = 0xA
WTS_SESSION_TERMINATE = 0xB

WTS_PERM_FLAGS_QUERY_INFORMATION = 0x0001
WTS_PERM_FLAGS_SET_INFORMATION = 0x0002
WTS_PERM_FLAGS_REMOTE_CONTROL = 0x0004
WTS_PERM_FLAGS_LOGON = 0x0008
WTS_PERM_FLAGS_LOGOFF = 0x0010
WTS_PERM_FLAGS_MESSAGE = 0x0020
WTS_PERM_FLAGS_CONNECT = 0x0040
WTS_PERM_FLAGS_DISCONNECT = 0x0080
WTS_PERM_FLAGS_VIRTUAL_CHANNEL = 0x0100

WTS_PERM_FLAGS_FULL = 0x0FFF # all permissions 
WTS_PERM_FLAGS_USER = WTS_PERM_FLAGS_CONNECT | WTS_PERM_FLAGS_QUERY_INFORMATION | WTS_PERM_FLAGS_LOGON | WTS_PERM_FLAGS_VIRTUAL_CHANNEL
WTS_PERM_FLAGS_GUEST = WTS_PERM_FLAGS_LOGON

MB_OK, MB_OKCANCEL, MB_ABORTRETRYIGNORE, MB_YESNOCANCEL, MB_YESNO, MB_RETRYCANCEL, MB_CANCELTRYCONTINUE = range(0, 7)

IDOK = 1
IDCANCEL = 2
IDABORT = 3
IDRETRY = 4
IDIGNORE = 5
IDYES = 6
IDNO = 7
IDTRYAGAIN = 10
IDCONTINUE = 11
IDTIMEOUT = 32000
IDASYNC = 32001

REMOTECONTROL_FLAG_DISABLE_KEYBOARD = 0x00000001
REMOTECONTROL_FLAG_DISABLE_MOUSE = 0x00000002
REMOTECONTROL_FLAG_DISABLE_INPUT = REMOTECONTROL_FLAG_DISABLE_KEYBOARD | REMOTECONTROL_FLAG_DISABLE_MOUSE

REMOTECONTROL_KBDSHIFT_HOTKEY = 0x1
REMOTECONTROL_KBDCTRL_HOTKEY  = 0x2
REMOTECONTROL_KBDALT_HOTKEY   = 0x4

MESSAGE_CUSTOM_TYPE = 1
MESSAGE_REQUEST_REMOTE_CONTROL = 2

# misc VK definitions
VK_ESCAPE = 0x1B

(VK_SPACE, VK_PRIOR, VK_NEXT, VK_END, VK_HOME, VK_LEFT, VK_UP, VK_RIGHT, VK_DOWN, VK_SELECT, VK_PRINT,
 VK_EXECUTE, VK_SNAPSHOT, VK_INSERT, VK_DELETE, VK_HELP) = range(0x20, 0x30)

(VK_KEY_0, VK_KEY_1, VK_KEY_2, VK_KEY_3, VK_KEY_4, VK_KEY_5, VK_KEY_6, VK_KEY_7, VK_KEY_8, VK_KEY_9) = range (0x30, 0x30 + 10)

(VK_KEY_A, VK_KEY_B, VK_KEY_C, VK_KEY_D, VK_KEY_E, VK_KEY_F, VK_KEY_G, VK_KEY_H, VK_KEY_I, VK_KEY_J, 
VK_KEY_K, VK_KEY_L, VK_KEY_M, VK_KEY_N, VK_KEY_O, VK_KEY_P, VK_KEY_Q, VK_KEY_R, VK_KEY_S, VK_KEY_T, 
VK_KEY_U, VK_KEY_V, VK_KEY_W, VK_KEY_X, VK_KEY_Y, VK_KEY_Z,
VK_LWIN, VK_RWIN, VK_APPS) = range(0x41, 0x5E)

(VK_NUMPAD0, VK_NUMPAD1, VK_NUMPAD2, VK_NUMPAD3, VK_NUMPAD4, VK_NUMPAD5, VK_NUMPAD6, VK_NUMPAD7, VK_NUMPAD8,
 VK_NUMPAD9) = range(0x60, 0x60 + 10)

(VK_F1, VK_F2, VK_F3, VK_F4, VK_F5, VK_F6, VK_F7, VK_F8, VK_F9, VK_F10, VK_F11, VK_F12) = range(0x70, 0x70 + 12)

VK = {
    VK_ESCAPE: 'Esc',
    VK_SPACE: 'space', VK_PRIOR: 'pageUp', VK_NEXT: 'pageDown', VK_END: 'end', VK_HOME: 'home', 
    VK_LEFT: 'left', VK_UP: 'up', VK_RIGHT: 'right', VK_DOWN: 'down', VK_SELECT: 'select', VK_PRINT: 'print',
    VK_EXECUTE: 'execute', VK_SNAPSHOT: 'snapshot', VK_INSERT: 'insert', VK_DELETE: 'delete', VK_HELP: 'help',
    
    VK_KEY_0: '0', VK_KEY_1: '1', VK_KEY_2: '2', VK_KEY_3: '3', VK_KEY_4: '4', VK_KEY_5: '5', VK_KEY_6: '6', 
    VK_KEY_7: '7', VK_KEY_8: '8', VK_KEY_9: '9',
    
    VK_KEY_A: 'a', VK_KEY_B: 'b', VK_KEY_C: 'c', VK_KEY_D: 'd', VK_KEY_E: 'e', VK_KEY_F: 'f', VK_KEY_G: 'g', 
    VK_KEY_H: 'h', VK_KEY_I: 'i', VK_KEY_J: 'j', VK_KEY_K: 'k', VK_KEY_L: 'l', VK_KEY_M: 'm', VK_KEY_N: 'n', 
    VK_KEY_O: 'o', VK_KEY_P: 'p', VK_KEY_Q: 'q', VK_KEY_R: 'r', VK_KEY_S: 's', VK_KEY_T: 't', VK_KEY_U: 'u', 
    VK_KEY_V: 'v', VK_KEY_W: 'w', VK_KEY_X: 'x', VK_KEY_Y: 'y', VK_KEY_Z: 'z',
    VK_LWIN: 'lwin', VK_RWIN: 'rwin', VK_APPS: 'apps',
    
    VK_NUMPAD0: 'pad0', VK_NUMPAD1: 'pad1', VK_NUMPAD2: 'pad2', VK_NUMPAD3: 'pad3', VK_NUMPAD4: 'pad4', VK_NUMPAD5: 'pad5', 
    VK_NUMPAD6: 'pad6', VK_NUMPAD7: 'pad7', VK_NUMPAD8: 'pad8', VK_NUMPAD9: 'pad9',
    
    VK_F1: 'F1', VK_F2: 'F2', VK_F3: 'F3', VK_F4: 'F4', VK_F5: 'F5', VK_F6: 'F6', VK_F7: 'F7', VK_F8: 'F8', 
    VK_F9: 'F9', VK_F10: 'F10', VK_F11: 'F11', VK_F12: 'F12'
}

# build the missing keys indexed by name and matching the VK_value
vkItems = [(k, v) for k, v in VK.items()]
for k, v in vkItems:
    VK[v] = k 


